Task 1
Data splitting--> want 1. correct split
2. stratified by age
3. seed=42
4. keeping the eval_data always locked

In [3]:
#load data development and evaluation
from functions import *

In [4]:
#data splitting 80-20 keeping eval locked
#stratified by age
#seed=42
dev_data = pd.read_csv("../data/development_data.csv", index_col=0)
#print("Development set", dev_data.shape, dev_data.head())
print("\n")
eval_data=pd.read_csv("../data/evaluation_data.csv", index_col=0)
#print("Evaluation set (locked)", eval_data.shape,eval_data.head())
print(len(dev_data),len(eval_data))

456 100

In [5]:
# Loading the eval and dev data through function
dev_data,eval_data=loading_files("../data/development_data.csv","../data/evaluation_data.csv")

Development set (456, 1003)            age             ethnicity sex  cg16867657  cg06639320  cg24724428  \
sample_id
GSM990554   79  Caucasian - European   M    0.672001    0.504461    0.331257
GSM990278   46    Hispanic - Mexican   M    0.555411    0.389214    0.160708
GSM990589   78  Caucasian - European   M    0.781318    0.554360    0.337578
GSM990323   46    Hispanic - Mexican   F    0.542491    0.435584    0.228723
GSM990116   59    Hispanic - Mexican   F    0.653190    0.466217    0.208453

           cg07553761  cg22454769  cg06784991  cg21572722  ...  cg17321954  \
sample_id                                                  ...
GSM990554    0.327287    0.572867    0.309496    0.444902  ...    0.174936
GSM990278    0.230875    0.464971    0.223665    0.381837  ...    0.154691
GSM990589    0.437668    0.645529    0.309615    0.505999  ...    0.213999
GSM990323    0.231709    0.493908    0.245836    0.424905  ...    0.198334
GSM990116    0.284740    0.592122    0.239320    0.434244  ...    0.147234

           cg17783401  cg26483332  cg22730412  cg14704921  cg12179661  \
sample_id
GSM990554    0.094635    0.163394    0.304777    0.093110    0.522947
GSM990278    0.043087    0.173311    0.343683    0.029271    0.496056
GSM990589    0.089760    0.173368    0.338127    0.066988    0.484525
GSM990323    0.121145    0.164312    0.394890    0.044809    0.510717
GSM990116    0.035716    0.156062    0.341784    0.024294         NaN

           cg16780603  cg00588614  cg13039082  cg16640358
sample_id
GSM990554    0.736352    0.262954    0.295386    0.350803
GSM990278    0.801962    0.291890    0.288421    0.318693
GSM990589    0.588307    0.276745    0.263589    0.344015
GSM990323    0.736712    0.287274    0.333076    0.303317
GSM990116    0.828072    0.256653    0.322450    0.370363

[5 rows x 1003 columns]


Evaluation set (locked) (100, 1003)            age             ethnicity sex  cg16867657  cg06639320  cg24724428  \
sample_id
GSM990599   65  Caucasian - European   F    0.713534    0.533543    0.338730
GSM989922   76  Caucasian - European   M    0.705395    0.472859    0.310131
GSM990306   63    Hispanic - Mexican   F    0.662773    0.481706    0.237187
GSM990320   59    Hispanic - Mexican   M    0.638065    0.456544    0.174587
GSM990002   71  Caucasian - European   F    0.695067    0.495763    0.276582

           cg07553761  cg22454769  cg06784991  cg21572722  ...  cg17321954  \
sample_id                                                  ...
GSM990599    0.364203    0.662077    0.291724    0.490470  ...    0.237585
GSM989922    0.358959    0.635802    0.287507         NaN  ...    0.206049
GSM990306    0.267787    0.602300    0.306610    0.453492  ...    0.189996
GSM990320    0.281471    0.614537    0.293233    0.436461  ...    0.169437
GSM990002    0.326186    0.662770    0.307118    0.405137  ...    0.176188

           cg17783401  cg26483332  cg22730412  cg14704921  cg12179661  \
sample_id
GSM990599    0.079218    0.165617    0.359383    0.085150    0.570230
GSM989922    0.096464    0.132663    0.280081    0.061219    0.536635
GSM990306    0.070674    0.182137    0.325564    0.052198    0.500524
GSM990320    0.064268    0.199800    0.317769    0.061953    0.528459
GSM990002    0.095870    0.184929    0.270476    0.047256    0.492331

           cg16780603  cg00588614  cg13039082  cg16640358
sample_id
GSM990599    0.800902    0.269018    0.290623    0.314786
GSM989922    0.744812    0.248199    0.262726    0.330051
GSM990306    0.725678    0.298588    0.334402    0.313727
GSM990320    0.748813    0.325457    0.329465    0.363478
GSM990002    0.792136    0.267520         NaN    0.346092

[5 rows x 1003 columns]
Samples of each data: 456 100

In [6]:
#Splitting the data into training and validation sets
#stratifying by age
X=dev_data
y=dev_data["age"]
y_bins=pd.qcut(y,5,duplicates='drop')

# Split the data
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y_bins)
total_data=len(X_train) + len(X_val)
train_pre= len(X_train)/ total_data*100
val_pre= len(X_val)/ total_data*100
print("Total samples of dev:",total_data)
print(f"Training set: {len(X_train)} samples ({train_pre:.2f}%)")
print(f"Validation set : {len(X_val)} samples ({val_pre:.2f}%)")

Total samples of dev: 456
Training set: 364 samples (79.82%)
Validation set : 92 samples (20.18%)

In [7]:
#function for splitting
def split_data(dev_data, eval_data):
    X=dev_data.drop(columns=["age"])
    y=dev_data["age"]
    #Bins Creation for stratification
    y_bins=pd.qcut(y,5,duplicates='drop')

    # Split the data
    X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42,stratify=y_bins)

    train_data=X_train.copy()
    train_data["age"]=y_train

    val_data=X_val.copy()
    val_data["age"]=y_val

    #Percentage Split
    total_data=len(train_data) + len(val_data)
    train_pre= len(train_data)/ total_data*100
    val_pre= len(val_data)/ total_data*100

    '''
    print("Total samples of dev:",total_data)
    print(f"Training set: {len(train_data)} samples ({train_pre:.2f}%)")
    print(f"Validation set : {len(val_data)} samples ({val_pre:.2f}%)")
    '''
    #Creating table of the data split information for better visualization
    table_summary = pd.DataFrame({
    "Split": ["Train", "Validation"],
    "Samples": [len(X_train), len(X_val)],
    "Percentage": [train_pre, val_pre]})
    print(table_summary)
    return train_data,val_data, eval_data

In [8]:
train_data,val_data,eval_data= split_data(dev_data,eval_data)

        Split  Samples  Percentage
0       Train      364   79.824561
1  Validation       92   20.175439

In [9]:
train_data.head(5)

,ethnicity,sex,cg16867657,cg06639320,cg24724428,cg07553761,cg22454769,cg06784991,cg21572722,cg24079702,...,cg17783401,cg26483332,cg22730412,cg14704921,cg12179661,cg16780603,cg00588614,cg13039082,cg16640358,age
sample_id,,,,,,,,,,,,,,,,,,,,,
GSM990121,Hispanic - Mexican,F,0.583677,0.432590,0.251182,0.313086,0.525740,0.265851,0.401995,0.363961,...,0.056080,0.184151,0.360041,0.043045,0.498758,0.742945,0.324369,0.296355,0.325072,64
GSM989978,Caucasian - European,M,0.630068,0.442362,0.258473,0.308090,0.547527,0.255296,0.418272,0.360343,...,0.092445,0.135585,0.320368,0.035074,0.478599,0.800113,0.261482,0.281599,0.324700,54
GSM990621,Caucasian - European,F,0.735531,0.484551,0.306418,0.326822,0.600015,0.279091,0.497256,0.402608,...,0.056014,0.159652,0.263493,0.065471,0.505322,0.736245,0.273843,0.282737,0.341408,70
GSM990064,Caucasian - European,M,0.804368,0.471031,0.330772,0.350285,0.653938,0.362480,0.464412,0.451967,...,0.262035,0.095317,0.256310,0.230947,0.431356,0.778582,0.237803,0.277310,0.293257,83
GSM990488,Hispanic - Mexican,M,0.654641,0.447308,0.244698,0.284639,0.584898,0.270158,0.442787,0.374594,...,0.102901,0.146249,0.326736,0.067682,0.529198,0.756666,0.245583,0.312507,0.326149,68

In [10]:
X_train.head(5)

,age,ethnicity,sex,cg16867657,cg06639320,cg24724428,cg07553761,cg22454769,cg06784991,cg21572722,...,cg17321954,cg17783401,cg26483332,cg22730412,cg14704921,cg12179661,cg16780603,cg00588614,cg13039082,cg16640358
sample_id,,,,,,,,,,,,,,,,,,,,,
GSM990121,64,Hispanic - Mexican,F,0.583677,0.432590,0.251182,0.313086,0.525740,0.265851,0.401995,...,0.198703,0.056080,0.184151,0.360041,0.043045,0.498758,0.742945,0.324369,0.296355,0.325072
GSM989978,54,Caucasian - European,M,0.630068,0.442362,0.258473,0.308090,0.547527,0.255296,0.418272,...,0.172218,0.092445,0.135585,0.320368,0.035074,0.478599,0.800113,0.261482,0.281599,0.324700
GSM990621,70,Caucasian - European,F,0.735531,0.484551,0.306418,0.326822,0.600015,0.279091,0.497256,...,0.194529,0.056014,0.159652,0.263493,0.065471,0.505322,0.736245,0.273843,0.282737,0.341408
GSM990064,83,Caucasian - European,M,0.804368,0.471031,0.330772,0.350285,0.653938,0.362480,0.464412,...,0.223823,0.262035,0.095317,0.256310,0.230947,0.431356,0.778582,0.237803,0.277310,0.293257
GSM990488,68,Hispanic - Mexican,M,0.654641,0.447308,0.244698,0.284639,0.584898,0.270158,0.442787,...,0.181087,0.102901,0.146249,0.326736,0.067682,0.529198,0.756666,0.245583,0.312507,0.326149

In [11]:
# Checking the missing values in the data
def check_missing_values(data):
    #Total missing values of data
    total_missing_values=data.isna().sum().sum()
    print("Total missing:",total_missing_values)
    #highlighting columns with most missing data
    miss_per_col= data.isna().sum()
    miss_per_col=miss_per_col[miss_per_col>0]
    sorted_miss= miss_per_col.sort_values(ascending=False)
    print("\nTop five missing:", sorted_miss.head(5))

In [12]:
#Searching for the NA values in each data set
print("Missing values in development set")
check_missing_values(dev_data)
print("Missing values in TRAIN set")
check_missing_values(train_data)
print("Missing values in VALIDATION set")
check_missing_values(val_data)
print("Missing values in EVALUATION set")
check_missing_values(eval_data)

Missing values in development set
Total missing: 13712

Top five missing: cg26330518    32
cg25410668    28
cg15903032    25
cg01493685    25
cg12233363    25
dtype: int64
Missing values in TRAIN set
Total missing: 10965

Top five missing: cg26330518    26
cg04193015    24
cg12233363    22
cg27314669    21
cg07234388    20
dtype: int64
Missing values in VALIDATION set
Total missing: 2747

Top five missing: cg01493685    9
cg07539927    8
cg03236802    8
cg15903032    8
cg25410668    8
dtype: int64
Missing values in EVALUATION set
Total missing: 3058

Top five missing: cg12233363    10
cg10979567     9
cg11419186     9
cg03013070     9
cg10891482     9
dtype: int64

In [13]:
# Gathering feature groups
metadata,cpg,age=feature_gathering(dev_data)
print("Metadata info:",metadata)
print("Info of CpG columns:",len(cpg))
print("Column of focus:",age)
print("=====================")
print(f"Feature Info: \n Metadata:{metadata},CpG columns:{len(cpg)},Column of focus: {age}")
#Create feature sets
metadata_features = feature_set(dev_data, sets="metadata")
cpg_features = feature_set(dev_data, sets="cpg")
all_features = feature_set(dev_data, sets="all")
print(f"Feature Count: \n Metadata:{len(metadata_features)},CpG columns:{len(cpg_features)},Column of focus: {len(all_features)}")
print("Metadata feature count:", len(metadata_features))
print("CpG feature count:", len(cpg_features))
print("All feature count:", len(all_features))

Metadata info: ['sex', 'ethnicity']
Info of CpG columns: 1000
Column of focus: age
=====================
Feature Info:
 Metadata:['sex', 'ethnicity'],CpG columns:1000,Column of focus: age
Feature Count:
 Metadata:2,CpG columns:1000,Column of focus: 1002
Metadata feature count: 2
CpG feature count: 1000
All feature count: 1002

In [14]:
# CpG feature matrix
X_train_cpg, y_train = split_feature(train_data, cpg_features, age="age")
X_val_cpg, y_val = split_feature(val_data, cpg_features, age="age")
X_eval_cpg, y_eval = split_feature(eval_data, cpg_features, age="age")

print("CpG matrix:")
print("Train_cpg:", X_train_cpg.shape)
print("Val_cpg:", X_val_cpg.shape)
print("Eval_cpg:", X_eval_cpg.shape)

print("==================================================")
#CpG preprocessing
preprocessor_cpg = preprocessor_pipeline(cpg=cpg_features, metadata=[])
X_train_cpg_processed = preprocessor_cpg.fit_transform(X_train_cpg) #only training fitting
X_val_cpg_processed = preprocessor_cpg.transform(X_val_cpg)
X_eval_cpg_processed = preprocessor_cpg.transform(X_eval_cpg)
print("Processed CpG-only")

CpG matrix:
Train_cpg: (364, 1000)
Val_cpg: (92, 1000)
Eval_cpg: (100, 1000)
==================================================
Processed CpG-only

In [15]:
#Creating a feature matrix
X_train_meta,y_train=split_feature(X_train,metadata_features,age="age")
X_val_meta,y_val=split_feature(X_val,metadata_features,age="age")
X_eval_meta,y_eval=split_feature(eval_data,metadata_features,age="age")
print("Metadata matrix:")
print("Train_metadata:", X_train_meta.shape)
print("Val_metadata:", X_val_meta.shape)
#print("Eval_meta:", X_eval_meta.shape)

print("==================================================")
#Metadata preprocessing
preprocessor_meta = preprocessor_pipeline(cpg=[], metadata=metadata_features)
X_train_meta_processed = preprocessor_meta.fit_transform(X_train_meta) #only on to be fitted
X_val_meta_processed = preprocessor_meta.transform(X_val_meta)
X_eval_meta_processed = preprocessor_meta.transform(X_eval_meta)

print("Processed Metadata matrix:")
print("Train_metadata_processed:", X_train_meta_processed.shape)
print("Val_metadata_processed:", X_val_meta_processed.shape)
print("Eval_meta_processed:", X_eval_meta_processed.shape)

Metadata matrix:
Train_metadata: (364, 2)
Val_metadata: (92, 2)
==================================================
Processed Metadata matrix:
Train_metadata_processed: (364, 4)
Val_metadata_processed: (92, 4)
Eval_meta_processed: (100, 4)

In [16]:
X_train_all, y_train = split_feature(X_train, all_features, age="age")
X_val_all, y_val = split_feature(X_val, all_features, age="age")
X_eval_all, y_eval = split_feature(eval_data,all_features, age="age")

print("All features matrices:")
print("Train_all:", X_train_all.shape)
print("Val_all:", X_val_all.shape)
print("Eval_all:", X_eval_all.shape)
print("==================================================")
#All feature preprocessing together
preprocessor_all = preprocessor_pipeline(cpg=cpg_features, metadata=metadata_features)
X_train_all_processed = preprocessor_all.fit_transform(X_train_all) #fit only here
X_val_all_processed = preprocessor_all.transform(X_val_all)
X_eval_all_processed = preprocessor_all.transform(X_eval_all)
print("Processed all feature matrices:")
print("Train_all_processed:", X_train_all_processed.shape)
print("Val_all_processed:", X_val_all_processed.shape)
print("Eval_all_processed:", X_eval_all_processed.shape)

All features matrices:
Train_all: (364, 1002)
Val_all: (92, 1002)
Eval_all: (100, 1002)
==================================================
Processed all feature matrices:
Train_all_processed: (364, 1004)
Val_all_processed: (92, 1004)
Eval_all_processed: (100, 1004)

In [17]:
def feature_matrices(train_data,val_data,eval_data):
    metadata_features,cpg_features,target=feature_gathering(train_data)
    all_features=metadata_features + cpg_features

    feature_groups={"metadata":metadata_features,"cpg":cpg_features,"all":all_features}
    store={}
    summaryofrows=[]

    for char, features in feature_groups.items():
        if len(features) == 0:
            print(f"No features found{char}.")
            continue
        X_train, y_train = split_feature(train_data, features, age=target)
        X_val, y_val = split_feature(val_data, features, age=target)
        X_eval, y_eval = split_feature(eval_data,all_features, age=target)
        # Preprocessor for each possible group build
        if char == "metadata":
         preprocessor = preprocessor_pipeline(cpg=[], metadata=features)
        elif char == "cpg":(
         preprocessor) = preprocessor_pipeline(cpg=features, metadata=[])
        else:
         preprocessor = preprocessor_pipeline(cpg=cpg_features, metadata=metadata_features)

         train_processed = preprocessor.fit_transform(X_train) #fit only here
         val_processed = preprocessor.transform(X_val)
         eval_processed = preprocessor.transform(X_eval)

    #Storing the features before after processing for summary table creation
         store[char] = { "features": features, "X_train": X_train,"y_train": y_train, "X_val": X_val,  "y_val": y_val,
            "X_eval": X_eval, "y_eval": y_eval,"train_processed": train_processed,"val_processed": val_processed,
            "eval_processed": eval_processed,"preprocessor": preprocessor }


    summary_data=pd.DataFrame(summaryofrows)
    return summary_data,store

In [18]:
store,summary_data=feature_matrices(train_data,val_data,eval_data)
#summary_data
store

Empty DataFrame
Columns: []
Index: []

In [19]:
def feature_matrices(train_data, val_data, eval_data):
    # Taking the features from previous function
    metadata_features, cpg_features, target = feature_gathering(train_data)
    all_features = metadata_features + cpg_features

    feature_groups = {"metadata": metadata_features, "cpg": cpg_features, "all": all_features }
    results = {}
    summary_rows = []

    for char, features in feature_groups.items():
        if len(features) == 0:
            print(f"Skipping {char}: no features found.")
            continue

        X_train, y_train = split_feature(train_data, features, age=target)
        X_val, y_val = split_feature(val_data, features, age=target)
        X_eval, y_eval = split_feature(eval_data, features, age=target)

       # Preprocessor for each possible group build
        if char == "metadata":
            preprocessor = preprocessor_pipeline(cpg=[], metadata=features)
        elif char == "cpg":
            preprocessor = preprocessor_pipeline(cpg=features, metadata=[])
        else:
            preprocessor = preprocessor_pipeline(cpg=cpg_features, metadata=metadata_features)

        # Fit on train only
        train_processed = preprocessor.fit_transform(X_train)
        val_processed = preprocessor.transform(X_val)
        eval_processed = preprocessor.transform(X_eval)

        # Store everything
        results[char] = { "features": features,
            "X_train": X_train, "y_train": y_train,
            "X_val": X_val, "y_val": y_val,
            "X_eval": X_eval, "y_eval": y_eval,
            "X_train_processed": train_processed, "X_val_processed": val_processed, "X_eval_processed": eval_processed,
            "preprocessor": preprocessor
        }

        # Summary row
        summary_rows.append({
            "feature_set": char,
            "train": X_train.shape,
            "train_processed": train_processed.shape,
            "val": X_val.shape,
            "val_processed": val_processed.shape,
            "evaluation": X_eval.shape,
            "evaluation_processed": eval_processed.shape
        })

    summary_df = pd.DataFrame(summary_rows)
    return results, summary_df

In [20]:
results, summary_df = feature_matrices(train_data, val_data, eval_data)
summary_df

,feature_set,train,train_processed,val,val_processed,evaluation,evaluation_processed
0,metadata,"(364, 2)","(364, 4)","(92, 2)","(92, 4)","(100, 2)","(100, 4)"
1,cpg,"(364, 1000)","(364, 1000)","(92, 1000)","(92, 1000)","(100, 1000)","(100, 1000)"
2,all,"(364, 1002)","(364, 1004)","(92, 1002)","(92, 1004)","(100, 1002)","(100, 1004)"

In [21]:
def data_summary(train, val, evaluation):
    rows = []
    for name, data in [("Train", train), ("Validation", val), ("Evaluation", evaluation)]:
        rows.append({"dataset":name,
             "samples": f"{len(data)}",
             "age_mean ± std": f"{data['age'].mean():.1f} ± {data['age'].std():.1f}",
             "age_range": f"{data['age'].min():.0f} - {data['age'].max():.0f}",
             "sex_balance": data["sex"].value_counts().to_dict() if "sex" in data.columns else {},
             "ethnicity_balance":data["ethnicity"].value_counts().to_dict() if "ethnicity" in data.columns else {},
             "total_missing_values": f"{int(data.isna().sum().sum())}"
             })
    stats_tab = pd.DataFrame(rows)
    return stats_tab

In [22]:
statistics_df = data_summary(train_data,val_data,eval_data)
statistics_df

,dataset,samples,age_mean ± std,age_range,sex_balance,ethnicity_balance,total_missing_values
0,Train,364,64.5 ± 14.6,19 - 101,"{'M': 191, 'F': 173}","{'Caucasian - European': 246, 'Hispanic - Mexi...",10965
1,Validation,92,64.2 ± 14.7,25 - 89,"{'F': 51, 'M': 41}","{'Caucasian - European': 62, 'Hispanic - Mexic...",2747
2,Evaluation,100,62.5 ± 14.3,21 - 92,"{'F': 58, 'M': 42}","{'Caucasian - European': 56, 'Hispanic - Mexic...",3058

In [23]:
def data_summary(train, val, evaluation, results=None, feature_set="all"):
    rows = []

    processed_map = {}
    processed_missing_map = {}

    if results is not None and feature_set in results:
        processed_map = {
            "Train": results[feature_set]["X_train_processed"].shape,
            "Validation": results[feature_set]["X_val_processed"].shape,
            "Evaluation": results[feature_set]["X_eval_processed"].shape
        }

        processed_missing_map = {
            "Train": pd.DataFrame(results[feature_set]["X_train_processed"]).isna().sum().sum(),
            "Validation": pd.DataFrame(results[feature_set]["X_val_processed"]).isna().sum().sum(),
            "Evaluation": pd.DataFrame(results[feature_set]["X_eval_processed"]).isna().sum().sum()
        }

    for name, data in [("Train", train), ("Validation", val), ("Evaluation", evaluation)]:
        rows.append({
            "dataset": name,
            "samples": len(data),
            "age_mean ± std": f"{data['age'].mean():.1f} ± {data['age'].std():.1f}",
            "age_range": f"{data['age'].min():.0f} - {data['age'].max():.0f}",
            "sex_balance": data["sex"].value_counts().to_dict() if "sex" in data.columns else {},
            "ethnicity_balance": data["ethnicity"].value_counts().to_dict() if "ethnicity" in data.columns else {},
            "total_missing_values_raw": int(data.isna().sum().sum()),
            "processed_shape": processed_map.get(name, None),
            "total_missing_values_processed": processed_missing_map.get(name, None)
        })

    return pd.DataFrame(rows)

In [24]:
stats_tab = data_summary(train_data,val_data,eval_data,results=results,feature_set="all")
stats_tab

,dataset,samples,age_mean ± std,age_range,sex_balance,ethnicity_balance,total_missing_values_raw,processed_shape,total_missing_values_processed
0,Train,364,64.5 ± 14.6,19 - 101,"{'M': 191, 'F': 173}","{'Caucasian - European': 246, 'Hispanic - Mexi...",10965,"(364, 1004)",0
1,Validation,92,64.2 ± 14.7,25 - 89,"{'F': 51, 'M': 41}","{'Caucasian - European': 62, 'Hispanic - Mexic...",2747,"(92, 1004)",0
2,Evaluation,100,62.5 ± 14.3,21 - 92,"{'F': 58, 'M': 42}","{'Caucasian - European': 56, 'Hispanic - Mexic...",3058,"(100, 1004)",0

In [25]:
def ols_model(train_data, y_train,val_data):
    model=LinearRegression()
    model.fit(train_data, y_train)
    y_predict=model.predict(val_data)
    return model,y_predict

#Evaluation function of each trained model on the validation set using bootstrap resampling of the validation set(1000 resamples, seed=42)
def evaluation_of_model (y_true,y_predict,n_bootstrap=100,seed=42):
    print("Evaluation of the model by using bootstrap")
    rng = np.random.RandomState(seed)
    y_true=np.array(y_true)
    y_predict=np.array(y_predict)

#RMSE, MAE, R², and Pearson r
    rmse_scores=[]
    mae_scores=[]
    r2_scores=[]
    pearson_corr_scores=[]
    indices = np.arange(len(y_true))

    for _ in range(n_bootstrap):
        sample_idx=rng.choice(indices, size=len(indices), replace=True)
        y_true_sample=y_true[sample_idx]
        y_pred_sample=y_predict[sample_idx]
        rmse=np.sqrt(mean_squared_error(y_true_sample, y_pred_sample))
        mae=mean_absolute_error(y_true_sample, y_pred_sample)
        r2=r2_score(y_true_sample, y_pred_sample)
        r, _=pearsonr(y_true_sample, y_pred_sample)
        rmse_scores.append(rmse)
        mae_scores.append(mae)
        r2_scores.append(r2)
        pearson_corr_scores.append(r)

    rmse_scores=np.array(rmse_scores)
    mae_scores=np.array(mae_scores)
    r2_scores=np.array(r2_scores)
    pearson_corr_scores=np.array(pearson_corr_scores)

    full_rmse=np.sqrt(mean_squared_error(y_true, y_predict))
    full_mae=mean_absolute_error(y_true, y_predict)
    full_r2=r2_score(y_true, y_predict)
    full_r, _=pearsonr(y_true, y_predict)

#Addind and with 95% confidence intervals (CI).
    final_results= {
        "rmse_mean": rmse_scores.mean(),
        "rmse_std": rmse_scores.std(ddof=1),
        "rmse_ci": np.percentile(rmse_scores, [2.5, 97.5]),
        "rmse_full": full_rmse,
        "rmse_scores": rmse_scores,

        "mae_mean": mae_scores.mean(),
        "mae_std": mae_scores.std(ddof=1),
        "mae_ci": np.percentile(mae_scores, [2.5, 97.5]),
        "mae_full": full_mae,
        "mae_scores": mae_scores,

        "r2_mean": r2_scores.mean(),
        "r2_std": r2_scores.std(ddof=1),
        "r2_ci": np.percentile(r2_scores, [2.5, 97.5]),
        "r2_full": full_r2,
        "r2_scores": r2_scores,

        "pearson_mean": pearson_corr_scores.mean(),
        "pearson_std": pearson_corr_scores.std(ddof=1),
        "pearson_ci": np.percentile(pearson_corr_scores, [2.5, 97.5]),
        "pearson_full": full_r,
        "pearson_scores":pearson_corr_scores
    }

    print("Validation metrics and 95% CI:")
    print(f"RMSE: {full_rmse:.4f} (95% CI: {final_results['rmse_ci'][0]:.4f} - {final_results['rmse_ci'][1]:.4f})")
    print(f"MAE: {full_mae:.4f} (95% CI: {final_results['mae_ci'][0]:.4f} - {final_results['mae_ci'][1]:.4f})")
    print(f"R^2: {full_r2:.4f} (95% CI: {final_results['r2_ci'][0]:.4f} - {final_results['r2_ci'][1]:.4f})")
    print(f"Pearson r: {full_r:.4f} (95% CI: {final_results['pearson_ci'][0]:.4f} - {final_results['pearson_ci'][1]:.4f})")
    return final_results

In [26]:
ols_meta_model,ols_meta_predict=ols_model(X_train_meta_processed,y_train,X_val_meta_processed)
ols_meta_results=evaluation_of_model(y_val,ols_meta_predict)

Evaluation of the model by using bootstrap
Validation metrics and 95% CI:
RMSE: 12.9545 (95% CI: 10.3478 - 14.9251)
MAE: 9.8540 (95% CI: 8.2050 - 11.5031)
R^2: 0.2138 (95% CI: 0.0706 - 0.3744)
Pearson r: 0.4629 (95% CI: 0.3346 - 0.6314)

In [27]:
ols_cpg_model, ols_cpg_predict = ols_model(X_train_cpg_processed,y_train,X_val_cpg_processed)
ols_cpg_results = evaluation_of_model(y_val,ols_cpg_predict)

Evaluation of the model by using bootstrap
Validation metrics and 95% CI:
RMSE: 5.2731 (95% CI: 4.2210 - 6.3661)
MAE: 4.0006 (95% CI: 3.3481 - 4.5064)
R^2: 0.8697 (95% CI: 0.8068 - 0.9171)
Pearson r: 0.9355 (95% CI: 0.9037 - 0.9615)

In [28]:
ols_all_model, ols_all_predict = ols_model(X_train_all_processed,y_train,X_val_all_processed)
ols_all_results = evaluation_of_model(y_val, ols_all_predict)

Evaluation of the model by using bootstrap
Validation metrics and 95% CI:
RMSE: 5.2576 (95% CI: 4.1987 - 6.3586)
MAE: 3.9915 (95% CI: 3.3598 - 4.5067)
R^2: 0.8705 (95% CI: 0.8074 - 0.9180)
Pearson r: 0.9360 (95% CI: 0.9042 - 0.9619)

In [29]:
def ols_all_featuresets(results, n_bootstrap=1000, seed=42):
    output = {}
    summary_rows = []

    for featureset in ["metadata", "cpg", "all"]:
        if featureset not in results:
            continue

        X_train = results[featureset]["X_train_processed"]
        X_val = results[featureset]["X_val_processed"]
        y_train = results[featureset]["y_train"]
        y_val = results[featureset]["y_val"]

        model, y_pred = ols_model(X_train, y_train, X_val)
        metrics = evaluation_of_model(y_val, y_pred, n_bootstrap=n_bootstrap, seed=seed)

        output[featureset] = {
            "model": model,
            "y_pred": y_pred,
            "metrics": metrics
        }

        summary_rows.append({
            "feature_set": featureset,
            "RMSE": round(metrics["rmse_full"], 4),
            "RMSE_95CI": f"{metrics['rmse_ci'][0]:.4f} - {metrics['rmse_ci'][1]:.4f}",
            "MAE": round(metrics["mae_full"], 4),
            "MAE_95CI": f"{metrics['mae_ci'][0]:.4f} - {metrics['mae_ci'][1]:.4f}",
            "R2": round(metrics["r2_full"], 4),
            "R2_95CI": f"{metrics['r2_ci'][0]:.4f} - {metrics['r2_ci'][1]:.4f}",
            "Pearson_r": round(metrics["pearson_full"], 4),
            "Pearson_95CI": f"{metrics['pearson_ci'][0]:.4f} - {metrics['pearson_ci'][1]:.4f}",
        })

    summary = pd.DataFrame(summary_rows)
    return output, summary

In [30]:
#Evaluation function run to each model separately on the validation set using bootstrap resampling of the validation set(1000 resamples, seed=42)
def evaluation_of_model (y_true,y_predict,n_bootstrap=1000,seed=42):

    rng = np.random.RandomState(seed)
    y_true=np.array(y_true)
    y_predict=np.array(y_predict)

#RMSE, MAE, R², and Pearson r
    rmse_scores=[]
    mae_scores=[]
    r2_scores=[]
    pearson_corr_scores=[]
    indices = np.arange(len(y_true))

    for _ in range(n_bootstrap):
        sample_idx=rng.choice(indices, size=len(indices), replace=True)
        y_true_sample=y_true[sample_idx]
        y_pred_sample=y_predict[sample_idx]

        rmse=np.sqrt(mean_squared_error(y_true_sample, y_pred_sample))
        mae=mean_absolute_error(y_true_sample, y_pred_sample)
        r2=r2_score(y_true_sample, y_pred_sample)
        r, _=pearsonr(y_true_sample, y_pred_sample)

        rmse_scores.append(rmse)
        mae_scores.append(mae)
        r2_scores.append(r2)
        pearson_corr_scores.append(r)

    rmse_scores=np.array(rmse_scores)
    mae_scores=np.array(mae_scores)
    r2_scores=np.array(r2_scores)
    pearson_corr_scores=np.array(pearson_corr_scores)

    full_rmse=np.sqrt(mean_squared_error(y_true, y_predict))
    full_mae=mean_absolute_error(y_true, y_predict)
    full_r2=r2_score(y_true, y_predict)
    full_r, _=pearsonr(y_true, y_predict)

#Addind and with 95% confidence intervals (CI).
    final_results= {
        "rmse_mean": rmse_scores.mean(),
        "rmse_std": rmse_scores.std(ddof=1),
        "rmse_ci": np.percentile(rmse_scores, [2.5, 97.5]),
        "rmse_full": full_rmse,
        "rmse_scores": r2_scores,

        "mae_mean": mae_scores.mean(),
        "mae_std": mae_scores.std(ddof=1),
        "mae_ci": np.percentile(mae_scores, [2.5, 97.5]),
        "mae_full": full_mae,

        "r2_mean": r2_scores.mean(),
        "r2_std": r2_scores.std(ddof=1),
        "r2_ci": np.percentile(r2_scores, [2.5, 97.5]),
        "r2_full": full_r2,
        "r2_scores": r2_scores,

        "pearson_mean": pearson_corr_scores.mean(),
        "pearson_std": pearson_corr_scores.std(ddof=1),
        "pearson_ci": np.percentile(pearson_corr_scores, [2.5, 97.5]),
        "pearson_full": full_r,
    }
    print("Evaluation completed")
    return final_results

#Train OLS LinearRegression model per feature set
def ols_all_featuresets(results, n_bootstrap=1000, seed=42):
    output = {}
    summary_rows = []

    for featureset in ["metadata", "cpg", "all"]:
        if featureset not in results:
            continue

        X_train = results[featureset]["X_train_processed"]
        X_val = results[featureset]["X_val_processed"]
        y_train = results[featureset]["y_train"]
        y_val = results[featureset]["y_val"]

        model, y_pred = ols_model(X_train, y_train, X_val)
        metrics = evaluation_of_model(y_val, y_pred, n_bootstrap=n_bootstrap, seed=seed)

        output[featureset] = {
            "model": model,
            "y_pred": y_pred,
            "metrics": metrics
        }

        summary_rows.append({
            "feature_set": featureset,
            "RMSE": round(metrics["rmse_full"], 4),
            "RMSE_95CI": f"{metrics['rmse_ci'][0]:.4f} - {metrics['rmse_ci'][1]:.4f}",
            "MAE": round(metrics["mae_full"], 4),
            "MAE_95CI": f"{metrics['mae_ci'][0]:.4f} - {metrics['mae_ci'][1]:.4f}",
            "R2": round(metrics["r2_full"], 4),
            "R2_95CI": f"{metrics['r2_ci'][0]:.4f} - {metrics['r2_ci'][1]:.4f}",
            "Pearson_r": round(metrics["pearson_full"], 4),
            "Pearson_95CI": f"{metrics['pearson_ci'][0]:.4f} - {metrics['pearson_ci'][1]:.4f}",
        })
        print(f"Train OLS LinearRegression for {featureset}")
    summary_df = pd.DataFrame(summary_rows)
    return output, summary_df

In [31]:
ols_results,ols_summary=ols_all_featuresets(results,n_bootstrap=1000,seed=42)
ols_summary

Evaluation completed
Train OLS LinearRegression for metadata
Evaluation completed
Train OLS LinearRegression for cpg
Evaluation completed
Train OLS LinearRegression for all

,feature_set,RMSE,RMSE_95CI,MAE,MAE_95CI,R2,R2_95CI,Pearson_r,Pearson_95CI
0,metadata,12.9545,10.5730 - 15.4597,9.8540,8.2067 - 11.7093,0.2138,0.0510 - 0.3648,0.4629,0.2991 - 0.6253
1,cpg,5.2731,4.0635 - 6.5458,4.0006,3.2965 - 4.6899,0.8697,0.7875 - 0.9235,0.9355,0.8930 - 0.9650
2,all,5.2576,4.0582 - 6.5256,3.9915,3.2988 - 4.6716,0.8705,0.7878 - 0.9243,0.9360,0.8937 - 0.9654

In [32]:
# Results of each model
#ElasticNet
print("###########Results############")
print("\n")
print("1.ElasticNet (EN) ")
elastic_model, elastic_pred = model_elasticnet(X_train_cpg_processed,y_train,X_val_cpg_processed)
elastic_results = evaluation_of_model(y_val, elastic_pred)
#SVR
print("\n2.SVR ")
svr_model, svr_pred = svr_model(X_train_cpg_processed,y_train,X_val_cpg_processed)
svr_results = evaluation_of_model(y_val, svr_pred)
#BayesianRidge
print("\n3.BayesianRidge (BR)")
bayes_model, bayes_pred = bayesianridge_model(X_train_cpg_processed,y_train,X_val_cpg_processed)
bayes_results = evaluation_of_model(y_val, bayes_pred)

###########Results############


1.ElasticNet (EN)
############### Training ElasticNet ###############
Evaluation completed

2.SVR
############### Training SVR ###############
Evaluation completed

3.BayesianRidge (BR)
############### Training BayesianRidge ###############
Evaluation completed

In [33]:
#Comparison table of models
comparison_table = pd.DataFrame([
    {
        "Model": "OLS",
        "RMSE": ols_cpg_results["rmse_full"],
        "MAE": ols_cpg_results["mae_full"],
        "R^2": ols_cpg_results["r2_full"],
        "Pearson_r": ols_cpg_results["pearson_full"],
    },
    {
        "Model": "EN",
        "RMSE": elastic_results["rmse_full"],
        "MAE": elastic_results["mae_full"],
        "R^2": elastic_results["r2_full"],
        "Pearson_r": elastic_results["pearson_full"],
    },
    {
        "Model": "SVR",
        "RMSE": svr_results["rmse_full"],
        "MAE": svr_results["mae_full"],
        "R^2": svr_results["r2_full"],
        "Pearson_r": svr_results["pearson_full"],
    },
    {
        "Model": "BR",
        "RMSE": bayes_results["rmse_full"],
        "MAE": bayes_results["mae_full"],
        "R^2": bayes_results["r2_full"],
        "Pearson_r": bayes_results["pearson_full"],
    }
])

comparison_table

  Model      RMSE       MAE       R^2  Pearson_r
0   OLS  5.273076  4.000551  0.869735   0.935548
1    EN  5.513114  4.093689  0.857606   0.933433
2   SVR  8.923338  6.473612  0.626962   0.846437
3    BR  4.728381  3.535510  0.895257   0.950015

In [34]:
#Checking for overfitting
models = {"OLS": ols_cpg_model,"EN": elastic_model,"SVR": svr_model,"BR": bayes_model}
train_val = train_vs_val_all_models(models, X_train_cpg_processed, y_train, X_val_cpg_processed, y_val)
train_val

  Model    Train RMSE  Val RMSE  Train R^2   Val R^2
0   OLS  7.348968e-14  5.273076   1.000000  0.869735
1    EN  3.841868e+00  5.513114   0.930916  0.857606
2   SVR  8.414715e+00  8.923338   0.668584  0.626962
3    BR  1.132770e+00  4.728381   0.993994  0.895257

In [35]:
#ElasticNet — L1+L2 regularised linear regression
def model_elasticnet(X_train,y_train,X_val):
    print("################Training of ElasticNet###############")
    model = ElasticNet()
    model.fit(X_train, y_train)
    y_predict = model.predict(X_val)
    return model, y_predict

#SVR — Support Vector Regression with RBF kernel
def svr_model(X_train,y_train,X_val):
    print("###############Training of SVR###############")
    model = SVR(kernel="rbf")
    model.fit(X_train, y_train)
    y_predict = model.predict(X_val)
    return model, y_predict

#BayesianRidge — Bayesian linear regression with automatic relevance determination
def bayesianridge_model(X_train, y_train, X_val):
    print("###############Training of BayesianRidge model###############")
    model = BayesianRidge()
    model.fit(X_train, y_train)
    y_predict = model.predict(X_val)
    return model, y_predict

#Derivables
#report_table
def report_table(results):
    rows = []
    for name, res in results.items():
        rows.append({
            "Model": name,
            "RMSE (mean ± CI)": f"{res['rmse_mean']:.4f} ({res['rmse_ci'][0]:.4f} - {res['rmse_ci'][1]:.4f})",
            "MAE": f"{res['mae_mean']:.4f}",
            "R^2": f"{res['r2_mean']:.4f}",
            "Pearson r": f"{res['pearson_mean']:.4f}"
        })

    df = pd.DataFrame(rows)
    print("Report table of Model Performance:")
    print(df.to_string(index=False))
    return df


#Boxplots
def bootstrap_boxplots(results, path="../figures/bootstrap_boxplots_rmse_r2.png"):
    os.makedirs("../figures", exist_ok=True)

    model_names = list(results.keys())
    rmse_data = [results[m]["metrics"]["rmse_scores"] for m in model_names]
    r2_data = [results[m]["metrics"]["r2_scores"] for m in model_names]

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    axes[0].boxplot(rmse_data, patch_artist=True)
    axes[0].set_title("Bootstrap RMSE Distribution")
    axes[0].set_ylabel("RMSE")
    axes[0].set_xlabel("Model")
    axes[0].set_xticks(range(1, len(model_names) + 1))
    axes[0].set_xticklabels(model_names, rotation=20)

    axes[1].boxplot(r2_data, patch_artist=True)
    axes[1].set_title("Bootstrap R² Distribution")
    axes[1].set_ylabel("R²")
    axes[1].set_xlabel("Model")
    axes[1].set_xticks(range(1, len(model_names) + 1))
    axes[1].set_xticklabels(model_names, rotation=20)

    plt.tight_layout()
    plt.savefig(path, dpi=300, bbox_inches="tight")
    plt.show()
    plt.close()

#Checking for overfitting
def train_vs_val_all_models(models, X_train, y_train, X_val, y_val):
    results = []
    for name, model in models.items():
        train_pred = model.predict(X_train)
        val_pred = model.predict(X_val)
        train_rmse = np.sqrt(mean_squared_error(y_train, train_pred))
        val_rmse = np.sqrt(mean_squared_error(y_val, val_pred))
        train_r2 = r2_score(y_train, train_pred)
        val_r2 = r2_score(y_val, val_pred)
        results.append({
            "Model": name,
            "Train RMSE": train_rmse,
            "Val RMSE": val_rmse,
            "Train R^2": train_r2,
            "Val R^2": val_r2
        })

    return pd.DataFrame(results)

In [36]:
def model_elasticnet(X_train, y_train, X_val):
    print("############### Training ElasticNet ###############")
    model = ElasticNet()
    model.fit(X_train, y_train)
    y_predict = model.predict(X_val)
    return model, y_predict

# SVR — Support Vector Regression with RBF kernel
def svr_model(X_train, y_train, X_val):
    print("############### Training SVR ###############")
    model = SVR(kernel="rbf")
    model.fit(X_train, y_train)
    y_predict = model.predict(X_val)
    return model, y_predict

# BayesianRidge — Bayesian linear regression
def bayesianridge_model(X_train, y_train, X_val):
    print("############### Training BayesianRidge ###############")
    model = BayesianRidge()
    model.fit(X_train, y_train)
    y_predict = model.predict(X_val)
    return model, y_predict


def report_table(results):
    rows = []
    for name, res in results.items():
        rows.append({
            "Model": name,
            "RMSE mean": f"{res['rmse_mean']:.4f}",
            "RMSE 95% CI": f"{res['rmse_ci'][0]:.4f} - {res['rmse_ci'][1]:.4f}",
            "MAE mean": f"{res['mae_mean']:.4f}",
            "MAE 95% CI": f"{res['mae_ci'][0]:.4f} - {res['mae_ci'][1]:.4f}",
            "R² mean": f"{res['r2_mean']:.4f}",
            "R² 95% CI": f"{res['r2_ci'][0]:.4f} - {res['r2_ci'][1]:.4f}",
            "Pearson r mean": f"{res['pearson_mean']:.4f}",
            "Pearson r 95% CI": f"{res['pearson_ci'][0]:.4f} - {res['pearson_ci'][1]:.4f}"
        })

    df = pd.DataFrame(rows)
    print("Report table of model performance:")
    print(df.to_string(index=False))
    return df


def bootstrap_boxplots(results, path="../figures/bootstrap_boxplots_rmse_r2.png"):
    os.makedirs("../figures", exist_ok=True)

    model_names = list(results.keys())
    rmse_data = [results[m]["rmse_scores"] for m in model_names]
    r2_data = [results[m]["r2_scores"] for m in model_names]

    fig, axes = plt.subplots(1, 2, figsize=(14, 6))

    axes[0].boxplot(rmse_data, patch_artist=True)
    axes[0].set_title("Bootstrap RMSE Distribution")
    axes[0].set_ylabel("RMSE")
    axes[0].set_xlabel("Model")
    axes[0].set_xticks(range(1, len(model_names) + 1))
    axes[0].set_xticklabels(model_names, rotation=20)

    axes[1].boxplot(r2_data, patch_artist=True)
    axes[1].set_title("Bootstrap R² Distribution")
    axes[1].set_ylabel("R²")
    axes[1].set_xlabel("Model")
    axes[1].set_xticks(range(1, len(model_names) + 1))
    axes[1].set_xticklabels(model_names, rotation=20)

    plt.tight_layout()
    plt.savefig(path, dpi=150, bbox_inches="tight")
    plt.show()
    plt.close()


def compare_with_ols_(model_results, ols_results):
    rows = []
    ols_rmse = ols_results["rmse_full"]
    ols_r2 = ols_results["r2_full"]

    for name, res in model_results.items():
        beats_ols = (res["rmse_full"] < ols_rmse) and (res["r2_full"] > ols_r2)
        rows.append({
            "Model": name,
            "RMSE": round(res["rmse_full"], 4),
            "R²": round(res["r2_full"], 4),
            "Beats OLS ": beats_ols
        })

    return pd.DataFrame(rows)

In [37]:
X_train_cpg = results["cpg"]["X_train_processed"]
X_val_cpg = results["cpg"]["X_val_processed"]
y_train = results["cpg"]["y_train"]
y_val = results["cpg"]["y_val"]
elastic_model, elastic_pred = model_elasticnet(X_train_cpg, y_train, X_val_cpg)
elastic_results = evaluation_of_model(y_val, elastic_pred, n_bootstrap=1000, seed=42)

svr_model_fit, svr_pred = svr_model(X_train_cpg, y_train, X_val_cpg)
svr_results = evaluation_of_model(y_val, svr_pred, n_bootstrap=1000, seed=42)

bayes_model, bayes_pred = bayesianridge_model(X_train_cpg, y_train, X_val_cpg)
bayes_results = evaluation_of_model(y_val, bayes_pred, n_bootstrap=1000, seed=42)
'''
baseline_results = {
    "OLS_CpG": ols_cpg_results,
    "ElasticNet": elastic_results,
    "SVR": svr_results,
    "BayesianRidge": bayes_results
}
report_df = report_table(baseline_results)
comparison_df = compare_with_ols(
    {
        "ElasticNet": elastic_results,
        "SVR": svr_results,
        "BayesianRidge": bayes_results
    },
    ols_cpg_results
)
bootstrap_boxplots(baseline_results)
'''

############### Training ElasticNet ###############
Evaluation completed
############### Training SVR ###############
Evaluation completed
############### Training BayesianRidge ###############
Evaluation completed

'\nbaseline_results = {\n    "OLS_CpG": ols_cpg_results,\n    "ElasticNet": elastic_results,\n    "SVR": svr_results,\n    "BayesianRidge": bayes_results\n}\nreport_df = report_table(baseline_results)\ncomparison_df = compare_with_ols(\n    {\n        "ElasticNet": elastic_results,\n        "SVR": svr_results,\n        "BayesianRidge": bayes_results\n    },\n    ols_cpg_results\n)\nbootstrap_boxplots(baseline_results)\n'

In [ ]:
#table asked
def query_table(model, stage_res):
    rows = []

    for stage, res in stage_res.items():
        rows.append({
            "Model": model,
            "Stage": stage,
            "RMSE_mean": f"{res['RMSE_mean']:.3f}",
            "95% CI": f"[{res['RMSE_CI'][0]:.3f}, {res['RMSE_CI'][1]:.3f}]",
            "MAE": f"{res['MAE_mean']:.3f}",
            "R²": f"{res['R2_mean']:.3f}",
            "Pearson r": f"{res['Pearson_mean']:.3f}"
        })

    df = pd.DataFrame(rows)
    print(df.to_string(index=False))
    return df

In [ ]:
elastic_stage_results = {"Baseline": elastic_results,"FS-only": elastic_fs,"FS+Tuned": elastic_tuned_results}
elastic_stage_table = query_table("ElasticNet", elastic_stage_results)
elastic_stage_table
svr_stage_results = {"Baseline": svr_results,"FS-only": svr_fs,"FS+Tuned": svr_tuned_results}
svr_stage_table = query_table("SVR", svr_stage_results)
svr_stage_table
bayes_stage_results ={"Baseline":bayes_results,"Fs-only":bayes_fs,"Fs+only":bayes_tuned_results}
bayes_stage_table = query_table("BayesianRidge", bayes_stage_results)
bayes_stage_table